from __future__ import annotations


def test_split_domain_routes_registered():
    import services.api_service.main as api_main

    routes = {route.path for route in api_main.app.routes}
    expected = {
        "/metrics",
        "/api/v1/pipelines",
        "/api/v1/pipelines/{topology_id}",
        "/api/v1/schemas",
        "/api/v1/schemas/{schema_id}/validate",
        "/api/v1/preview/topics",
        "/api/v1/preview/topics/{topic}",
        "/api/v1/preview/topics/{topic}/peek",
        "/api/v1/connectors",
        "/api/v1/connectors/{connector_id}",
        "/api/v1/modeling/models",
        "/api/v1/modeling/tools",
        "/api/v1/modeling/prompts",
        "/api/v1/modeling/context",
        "/api/v1/search/catalog",
        "/api/v1/search/plan",
        "/api/v1/search/semantic",
        "/api/v1/search/hybrid",
        "/api/v1/search/index/rebuild",
        "/api/v1/search/index/evaluate",
        "/api/v1/semantic/core",
        "/api/v1/semantic/graph",
        "/api/v1/semantic/graph/search",
        "/api/v1/semantic/graph/entities/{entity_id:path}",
        "/api/v1/semantic/graph/relationships/{relationship_id:path}",
        "/api/v1/semantic/ontology-packs",
        "/api/v1/semantic/entities",
        "/api/v1/semantic/relationships",
        "/api/v1/semantic/documents",
        "/api/v1/semantic/workflows",
        "/api/v1/semantic/observations",
        "/api/v1/semantic/lineage",
        "/api/v1/retrieval/catalog",
        "/api/v1/retrieval/search",
        "/api/v1/digital-twin/scenes/{scene_id}",
        "/api/v1/digital-twin/scenes/{scene_id}/entities/{entity_id}/values",
        "/api/v1/oee/shifts",
        "/api/v1/oee/calculate",
        "/api/v1/assets/external",
        "/api/v1/assets/external/{asset_id}",
        "/api/v1/assets/external/{asset_id}/tags",
        "/api/v1/events/external",
        "/api/v1/historian/backup",
        "/api/v1/historian/restore",
        "/api/v1/historian/backups",
        "/api/v1/historian/backup/status",
        "/api/v1/reports/templates",
        "/api/v1/reports/generate/{template_id}",
        "/api/v1/reports",
        "/api/v1/reports/schedule/{template_id}",
    }
    missing = expected - routes
    assert not missing, f"missing routes: {sorted(missing)}"
