FROM flink:1.20.0-scala_2.12-java17

WORKDIR /opt/stream

COPY services /opt/stream/services
COPY config /opt/stream/config
COPY requirements.txt /opt/stream/requirements.txt

ENV PYTHONPATH=/opt/stream

CMD ["bash", "-lc", "flink run -py /opt/stream/services/processor/iot_anomaly_job.py -pyfs /opt/stream"]
