FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY services ./services
COPY config ./config

ENV PYTHONPATH=/app

EXPOSE 8020

CMD ["python", "-m", "uvicorn", "services.api_service.main:app", "--host", "0.0.0.0", "--port", "8020", "--no-access-log"]
