#!/usr/bin/env bash
set -Eeuo pipefail

# Install the complete Docker Compose Site Server on a Linux host. The script
# deliberately does not install Docker or create secrets; those are operator
# and distribution concerns that vary across industrial environments.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
BUNDLE_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
INSTALL_DIR="${RAVAN_INSTALL_DIR:-/opt/ravan}"
SITE_ID="${RAVAN_SITE_ID:-demo-site}"
MODE="${RAVAN_INSTALL_MODE:-source-build}"
SERVICE_NAME="${RAVAN_SERVICE_NAME:-ravan-site}"
PROJECT_NAME="${RAVAN_PROJECT_NAME:-ravan-${SITE_ID}}"
IMAGE_REGISTRY="${RAVAN_IMAGE_REGISTRY:-ghcr.io/navid-moradimehr}"
VERSION="${RAVAN_VERSION:-1.0.0-beta.1}"
NO_START=0
FORCE=0

usage() {
  cat <<'EOF'
Usage: install.sh [options]

Install a complete Ravan Site Server from this release bundle.

Options:
  --mode MODE          source-build (default) or registry
  --site-id ID         site identity (default: demo-site)
  --target-dir PATH    install root (default: /opt/ravan)
  --service-name NAME  systemd service name (default: ravan-site)
  --project-name NAME  Docker Compose project name
  --version VERSION    Ravan image version for registry mode
  --image-registry URL registry host/path for registry mode
  --no-start           install files and service, but do not start it
  --force              allow replacing an existing service definition
  -h, --help           show this help
EOF
}

die() {
  echo "Ravan installer: $*" >&2
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mode) MODE="${2:?missing value for --mode}"; shift 2 ;;
    --site-id) SITE_ID="${2:?missing value for --site-id}"; shift 2 ;;
    --target-dir) INSTALL_DIR="${2:?missing value for --target-dir}"; shift 2 ;;
    --service-name) SERVICE_NAME="${2:?missing value for --service-name}"; shift 2 ;;
    --project-name) PROJECT_NAME="${2:?missing value for --project-name}"; shift 2 ;;
    --version) VERSION="${2:?missing value for --version}"; shift 2 ;;
    --image-registry) IMAGE_REGISTRY="${2:?missing value for --image-registry}"; shift 2 ;;
    --no-start) NO_START=1; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown option: $1" ;;
  esac
done

[[ "$MODE" == "source-build" || "$MODE" == "registry" ]] || die "--mode must be source-build or registry"
[[ "$SITE_ID" =~ ^[A-Za-z0-9._-]+$ ]] || die "site id contains unsupported characters: $SITE_ID"
[[ "$SERVICE_NAME" =~ ^[A-Za-z0-9@._-]+$ ]] || die "service name contains unsupported characters: $SERVICE_NAME"
[[ "$PROJECT_NAME" =~ ^[A-Za-z0-9._-]+$ ]] || die "project name contains unsupported characters: $PROJECT_NAME"
[[ -d "$BUNDLE_ROOT/runtime/docker" ]] || die "runtime/docker is missing from the release bundle"
[[ -f "$BUNDLE_ROOT/site/${SITE_ID}.env" ]] || die "site/${SITE_ID}.env is missing from the release bundle"

if [[ "$(id -u)" -ne 0 ]]; then
  command -v sudo >/dev/null 2>&1 || die "run as root or install sudo"
  exec sudo -E bash "$0" "$@"
fi

command -v docker >/dev/null 2>&1 || die "Docker Engine is required; install and start Docker, then retry"
docker compose version >/dev/null 2>&1 || die "Docker Compose v2 plugin is required; install it, then retry"

COMPOSE_FILE="${INSTALL_DIR}/runtime/docker/docker-compose.yml"
if [[ "$MODE" == "registry" ]]; then
  [[ -f "$BUNDLE_ROOT/runtime/docker/docker-compose.release.yml" ]] || die "registry mode requires docker-compose.release.yml"
  COMPOSE_FILE="${INSTALL_DIR}/runtime/docker/docker-compose.release.yml"
fi

mkdir -p "$INSTALL_DIR" "$INSTALL_DIR/runtime" "$INSTALL_DIR/site" \
  "$INSTALL_DIR/data" "$INSTALL_DIR/logs" "$INSTALL_DIR/backups" \
  "$INSTALL_DIR/.datastream" "$INSTALL_DIR/bin"

SERVICE_PATH="/etc/systemd/system/${SERVICE_NAME}.service"
if [[ -f "$SERVICE_PATH" && "$FORCE" -ne 1 ]]; then
  die "${SERVICE_PATH} already exists; use --force to replace it"
fi

# Runtime source/config is replaceable. Operator state and .env are not.
cp -a "$BUNDLE_ROOT/runtime/." "$INSTALL_DIR/runtime/"
cp -a "$BUNDLE_ROOT/site/." "$INSTALL_DIR/site/"

ENV_FILE="$INSTALL_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  if [[ -f "$INSTALL_DIR/runtime/.env.production.example" ]]; then
    cp "$INSTALL_DIR/runtime/.env.production.example" "$ENV_FILE"
  else
    : > "$ENV_FILE"
  fi
  {
    echo
    echo "# Site identity generated by the Ravan installer."
    cat "$INSTALL_DIR/site/${SITE_ID}.env"
  } >> "$ENV_FILE"
fi

# Registry settings are only defaults. Existing operator values always win.
if ! grep -q '^RAVAN_IMAGE_REGISTRY=' "$ENV_FILE"; then
  printf 'RAVAN_IMAGE_REGISTRY=%s\n' "$IMAGE_REGISTRY" >> "$ENV_FILE"
fi
if ! grep -q '^RAVAN_VERSION=' "$ENV_FILE"; then
  printf 'RAVAN_VERSION=%s\n' "$VERSION" >> "$ENV_FILE"
fi
if ! grep -q '^PROJECT_NAME=' "$ENV_FILE"; then
  printf 'PROJECT_NAME=%s\n' "$PROJECT_NAME" >> "$ENV_FILE"
fi

INSTALL_ENV="$INSTALL_DIR/.datastream/install.env"
cat > "$INSTALL_ENV" <<EOF
RAVAN_INSTALL_DIR=$(printf '%q' "$INSTALL_DIR")
RAVAN_SITE_ID=$(printf '%q' "$SITE_ID")
RAVAN_INSTALL_MODE=$(printf '%q' "$MODE")
RAVAN_SERVICE_NAME=$(printf '%q' "$SERVICE_NAME")
RAVAN_PROJECT_NAME=$(printf '%q' "$PROJECT_NAME")
RAVAN_ENV_FILE=$(printf '%q' "$ENV_FILE")
RAVAN_COMPOSE_FILE=$(printf '%q' "$COMPOSE_FILE")
EOF
chmod 600 "$INSTALL_ENV" "$ENV_FILE"

DOCKER_BIN="$(command -v docker)"
cat > "$SERVICE_PATH" <<EOF
[Unit]
Description=Ravan Industrial Data Site Server (${SITE_ID})
Documentation=https://github.com/Navid-Moradimehr/Ravan
Wants=network-online.target
After=network-online.target docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${INSTALL_DIR}/runtime
ExecStart=${DOCKER_BIN} compose --project-name ${PROJECT_NAME} --env-file ${ENV_FILE} --file ${COMPOSE_FILE} --profile ui --profile edge up -d
ExecStop=${DOCKER_BIN} compose --project-name ${PROJECT_NAME} --env-file ${ENV_FILE} --file ${COMPOSE_FILE} --profile ui --profile edge stop
ExecReload=${DOCKER_BIN} compose --project-name ${PROJECT_NAME} --env-file ${ENV_FILE} --file ${COMPOSE_FILE} --profile ui --profile edge up -d
TimeoutStartSec=0
TimeoutStopSec=120

[Install]
WantedBy=multi-user.target
EOF

cat > "$INSTALL_DIR/bin/ravan-site" <<'EOF'
#!/usr/bin/env bash
set -Eeuo pipefail
TARGET_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
source "$TARGET_DIR/.datastream/install.env"
case "${1:-status}" in
  start|stop|restart|status|enable|disable)
    exec systemctl "$1" "${RAVAN_SERVICE_NAME}.service"
    ;;
  logs)
    exec docker compose --project-name "$RAVAN_PROJECT_NAME" --env-file "$RAVAN_ENV_FILE" --file "$RAVAN_COMPOSE_FILE" logs --tail="${2:-200}" -f
    ;;
  doctor)
    exec "$TARGET_DIR/bin/doctor.sh" "${@:2}"
    ;;
  uninstall)
    exec "$TARGET_DIR/bin/uninstall.sh" "${@:2}"
    ;;
  *)
    echo "Usage: ravan-site {start|stop|restart|status|enable|disable|logs|doctor|uninstall}" >&2
    exit 2
    ;;
esac
EOF
chmod 755 "$INSTALL_DIR/bin/ravan-site"

cp "$SCRIPT_DIR/ravan-site-doctor.sh" "$INSTALL_DIR/bin/doctor.sh"
cp "$SCRIPT_DIR/uninstall-linux-site-server.sh" "$INSTALL_DIR/bin/uninstall.sh"
chmod 755 "$INSTALL_DIR/bin/doctor.sh" "$INSTALL_DIR/bin/uninstall.sh"

systemctl daemon-reload
systemctl enable "${SERVICE_NAME}.service" >/dev/null

compose() {
  "$DOCKER_BIN" compose --project-name "$PROJECT_NAME" --env-file "$ENV_FILE" --file "$COMPOSE_FILE" --profile ui --profile edge "$@"
}

compose config --quiet || die "Compose configuration is invalid; inspect ${ENV_FILE}"
if [[ "$NO_START" -eq 0 ]]; then
  if [[ "$MODE" == "registry" ]]; then
    compose pull
  else
    compose build
  fi
  systemctl start "${SERVICE_NAME}.service"
fi

cat <<EOF
Ravan Site Server installed.
  root: ${INSTALL_DIR}
  site: ${SITE_ID}
  mode: ${MODE}
  service: ${SERVICE_NAME}.service
  dashboard: http://localhost:${DASHBOARD_HOST_PORT:-3006}
  api: http://localhost:${API_SERVICE_HOST_PORT:-8020}/health

Use: ${INSTALL_DIR}/bin/ravan-site status
Doctor: sudo ${INSTALL_DIR}/bin/ravan-site doctor
Data-preserving uninstall: sudo ${INSTALL_DIR}/bin/ravan-site uninstall
EOF
